### ISSUE TITLE
Consider making a Homebridge version

### ISSUE THREAD

**Issue by DennisJohnsen** [oh2th-homey/com.balboa#1]
Hey

First off, great work on this App for Homey. My neighboor showed it too me, and hes happy with it for his smarthome setup.
Unfortunatly i use Homekit, and thus Homebridge for a lot of my devices.

Could i get you to consider looking at a Homebridge version of this app?

Kind regards, Dennis

**Comment by martijnpoppen** [comment]
Hi Dennis,
There is a homebridge version available.
The Homey app uses the same library

https://github.com/apexad/homebridge-eufy-robovac

Hope this answers your question

**Comment by martijnpoppen** [comment]
Hey @DennisJohnsen 
Unfortunately i don't create homebridge apps.
I'm mainly focussed on the Homey ecosystem

But there is a library available to implement this in a app. I used it too for this app. Library: https://gitlab.com/VVlasy/controlmyspajs

Maybe you can find a homebridge developer to work on it 

Good Luck!

**Comment by DennisJohnsen** [comment]
> Hey @DennisJohnsen Unfortunately i don't create homebridge apps. I'm mainly focussed on the Homey ecosystem
> 
> But there is a library available to implement this in a app. I used it too for this app. Library: https://gitlab.com/VVlasy/controlmyspajs
> 
> Maybe you can find a homebridge developer to work on it
> 
> Good Luck!

 No worries, I thought I would give it a ask.
Maybe most of your code base can be reused :) might give it a go my self, but i only just recently got into typescript 😅


Have a great day!
