### ISSUE TITLE
measure and target values trigger when null becomes real value

### ISSUE THREAD

**Issue by oh2th** [oh2th-homey/com.balboa#4]
On init of device (when app has been restarted) the some of the triggers are activated.
For example I have a flow looking at when the target_temperature changes, the new target_temperature is posted to timeline.
Not sure how to prevent the initial value change from null from triggering the trigger.

**Comment by martijnpoppen** [comment]
Will check this. I don have a `firstRun` check in the app for this.

**Comment by oh2th** [comment]
I think is something of a default by Homey, that it creates those triggers automatically for measure_ and target_
as it says it here https://apps.developer.homey.app/the-basics/flow
"Often it is not necessary to define your own Flow cards because most device classes and capabilities automatically add their own Flow cards."

**Comment by martijnpoppen** [comment]
Ah yes,
I only check the custom FlowCards :/ 

Hmm wondering if this could be fixed

**Comment by martijnpoppen** [comment]
I did do some checks but this is default behaviour of Homey which can't be changed unfortunately
