### ISSUE TITLE
Add CIRCULATION_PUMP component status

### ISSUE THREAD

**Issue by oh2th** [oh2th-homey/com.balboa#8]
Tells of the filtration cycle is running. And together with HEATING ON:OFF, it an be used to know if it filtration cycle or just because heating is require.
    {
      componentType: 'CIRCULATION_PUMP',
      materialType: 'CIRCULATION_PUMP',
      value: 'OFF',
      availableValues: [Array],
      name: 'CIRCULATION_PUMP',
      registeredTimestamp: '2023-01-21T06:14:49.181+0000'
    },

**Comment by martijnpoppen** [comment]
@oh2th See PR :)
